version: '3'

services:
    mssql-bacpac:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        command: >
            /bin/bash -c "
            echo 'Installing sqlpackage tool...';
            export PATH=/root/.dotnet/tools:/usr/share/dotnet:/usr/bin;
            dotnet tool update microsoft.sqlpackage --global --verbosity minimal;

            echo 'Importing bacpac...';
            sqlpackage /Action:Import
            /TargetDatabaseName:seas
            /TargetServerName:seas-mssql
            /TargetUser:sa
            /TargetPassword:'${DB_PASSWORD}'
            /SourceFile:/tmp/new_seas.bacpac
            /TargetTrustServerCertificate:true
            /TargetTimeout:5;"
        volumes:
            - ./docker/mssql/backups/new_seas.bacpac:/tmp/new_seas.bacpac
        networks:
            - seas_bancaplus

networks:
    seas_bancaplus:
        driver: "bridge"

volumes:
    seasdata:
